### ISSUE TITLE
训练结果与脑电图匹配问题

### ISSUE THREAD

**Issue by NZW666666** [prajwalsingh/EEG2Image#14]
作者您好，就是我想问一下训练出来的结果图对应的脑电图是怎么样的啊？怎么知道哪些脑电波对应生成苹果，哪些脑电波对应生成手表呢？谢谢

**Comment by prajwalsingh** [comment]
您好，由于实验设置的原因，ThoughtViz 数据集中没有此类对应关系。该图像被展示给参与者，随后他们要求可视化数据集，并在此期间收集数据。因此，苹果或任何其他物体的任何可能的图像都可以与给定类别的脑电图配对。

因此，根据实验：假设显示了第 1 类的某个数字，然后要求参与者可视化第 1 类数字 10 秒，相当于收集了脑电图数据。因此，我们可以使用任何 1 类数字图像作为 EEG 信号的一对。

( Hi, there is no such correspondence in the ThoughtViz dataset due to the experimental setup. The image is shown to a participant and later they ask to visualise the dataset and during that time data is collected. So any possible image of an apple or any other object can be pair for a given class of EEG.

So as per the experiment: let say some digit of class 1 is shown and after that participants were asked to visualise class 1 digit for 10 seconds and equivalent to that EEG data is collected. So we can use any class 1 digit image as a pair to the EEG signal. )

**Comment by NZW666666** [comment]
那怎么知道生成的图像与你看到的图像是否匹配呢，那个date.pkl文件里是包含苹果，手表等等所有的类别的脑电图吗

**Comment by prajwalsingh** [comment]
根据实验设置，向用户显示的图像不一定是用户准确想象的。例如，用户可以尝试可视化一个苹果，它可以是数据集中任何类型的苹果图像，因此我们可以将任何苹果与为苹果收集的脑电图相关联。

是的，pkl 文件中的数据包含特定类别的所有 EEG，并且其他数据集有不同的 pkl 文件。

(As per the experimental setup, it is not necessary that the image shown to user will be accurately imagined by the user. For example user can try to visualize an apple and it can be any type of apple images from the dataset, so we can associate any apple to EEG collected for apple.

Yes, the data in the pkl file contains all the EEGs for specific classes, and there are different pkl files for other datasets.)

**Comment by NZW666666** [comment]
那可不可以把.pkl文件里那些不同类别的分开呢，那样结果对比会不会更清晰一定呢

**Comment by prajwalsingh** [comment]
为了与 EEG2Image 论文进行比较，我们遵循 ThoughtViz 研究论文的实验设置。

您可以按照任何实验设置来复制该研究。您可以拆分类别并研究网络的性能。

(For comparison in the EEG2Image paper, we have followed the experimental setup of ThoughtViz research paper. 

You can follow any experimental setup to replicate the study. You can split the categories and study how the network is performing.)

**Comment by NZW666666** [comment]
哦哦好的谢谢您的回复
