### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by ghost** [prajwalsingh/EEG2Image#6]
Hello, not a programmer so sorry for stupid question. How do I use this to generate images from eeg brain waves I have? I can't find instructions anywhere.

**Comment by prajwalsingh** [comment]
Hi,  thank you for checking our work. 

Following are the instructions on how to use:

1. Download or Git clone the repository after that download checkpoints and dataset.
2. Create the anaconda environment  using the shared yml file.
3. Keep the checkpoints in experiments/best_ckpt and place the downloaded data after extraction in data folder.
4. After the above step, run the code test_generation.py it will load the test data from data folder and generate the result and save it in experiments folder.

If you want to run it on your own EEG data, I will suggest you to go through research paper. For own data you have to first train LSTM network for feature extraction from EEG dataset and later you have to train the GAN network for image generation.

Let me know if you need any further help.

**Comment by ghost** [comment]
Thanks a ton. Just so I'm clear, each individual person who wants to use their own eeg data has to do all the training for their own data? Or once you do all the training it will work with any eeg data?

**Comment by prajwalsingh** [comment]
It depends on the device that has been used for collecting the EEG data. The dataset we have used is collected using the Emotiv Con 14 Channel device. If the EEG data that you want to reconstruct is collected from a similar device, then you can directly use the pre-trained weights given here for the reconstruction of images.

So if the dataset is collected using the same device, then once you train the network on a given dataset, it can later be used for different EEG data collected from the same device.

Generalizing the learning regime across different channel EEG datasets is still an open problem over which researchers are working at present.

**Comment by ghost** [comment]
Thankyou. So if I collect eeg data from the emotiv con 14 channel device, I can use the model you already have without having to do any training myself or anything?

**Comment by prajwalsingh** [comment]
15-30% probability of working fine for image generation. You can find our recent work [https://arxiv.org/pdf/2310.16532v1.pdf](Learning Robust Deep Visual Representations from EEG Brain Recordings)(WACV24), where in section 4.2 (Figure 6), we have performed an experiment to show zero-shot performance for feature extraction but this has been done for the same set of human subjects. The one major problem still there is Subject Invariance in EEG data.

If you can perform the experiment and collect fresh data with the help of Emotiv Con 14 Channel and try our method, then 15-30% chance that it might work for subject invariance. Your experiments result will be a big help for us also because it will provide new insights as well as verification of the proposed method in live reconstruction.

This probability score (15-30%) was obtained from earlier experiments that we have performed for subject invariance testing.

**Comment by ghost** [comment]
Thankyou so much! I will definitely be reading through all this some more and let you know any results I get. Thanks again for all the info.

**Comment by prajwalsingh** [comment]
You're welcome. Thank you.
