### ISSUE TITLE
about the generated image

### ISSUE THREAD

**Issue by qiuyuesong** [prajwalsingh/EEG2Image#8]
While attempting to replicate your research, I observed an unexpected outcome where a specific category of EEG data generated images associated with a different category. For instance, when utilizing test EEG data categorized as 'rose,' the resulting generated image corresponds to the 'wallet' category. I'm uncertain if you've encountered a similar issue during your work. Could you provide insights or guidance on potential reasons for this discrepancy

**Comment by prajwalsingh** [comment]
Hi, the result you are getting is expected because the EEG features might overlap with some other classes, and the same can be seen from the tSNE plot mentioned in the paper.  You can also check our following work accepted in WACV24 Learning Robust Deep Visual Representations from EEG Brain Recordings [https://arxiv.org/pdf/2310.16532v1.pdf] where at last page, you can find a collage which shows if we improve the feature extraction network ambiguity will also be less.
